# Generated by Django 5.2.4 on 2025-07-08 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeping', '0006_customer_contact_person_alter_customer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='enable_finance_charge',
            field=models.BooleanField(default=True, help_text='Enable automatic finance charge calculation'),
        ),
    ]
